# Generated by Django 5.2.6 on 2026-06-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
