# Generated by Django 5.2.6 on 2026-06-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
